/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.minisql.rpc.master;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2026-05-12")
public class HeartbeatRequest implements org.apache.thrift.TBase<HeartbeatRequest, HeartbeatRequest._Fields>, java.io.Serializable, Cloneable, Comparable<HeartbeatRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HeartbeatRequest");

  private static final org.apache.thrift.protocol.TField REGION_SERVER_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("regionServerIp", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("port", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField LOAD_SCORE_FIELD_DESC = new org.apache.thrift.protocol.TField("loadScore", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField HOLDING_REGIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("holdingRegions", org.apache.thrift.protocol.TType.LIST, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new HeartbeatRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new HeartbeatRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String regionServerIp; // required
  public int port; // required
  public int loadScore; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> holdingRegions; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REGION_SERVER_IP((short)1, "regionServerIp"),
    PORT((short)2, "port"),
    LOAD_SCORE((short)3, "loadScore"),
    HOLDING_REGIONS((short)4, "holdingRegions");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REGION_SERVER_IP
          return REGION_SERVER_IP;
        case 2: // PORT
          return PORT;
        case 3: // LOAD_SCORE
          return LOAD_SCORE;
        case 4: // HOLDING_REGIONS
          return HOLDING_REGIONS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PORT_ISSET_ID = 0;
  private static final int __LOADSCORE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REGION_SERVER_IP, new org.apache.thrift.meta_data.FieldMetaData("regionServerIp", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PORT, new org.apache.thrift.meta_data.FieldMetaData("port", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LOAD_SCORE, new org.apache.thrift.meta_data.FieldMetaData("loadScore", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.HOLDING_REGIONS, new org.apache.thrift.meta_data.FieldMetaData("holdingRegions", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HeartbeatRequest.class, metaDataMap);
  }

  public HeartbeatRequest() {
  }

  public HeartbeatRequest(
    java.lang.String regionServerIp,
    int port,
    int loadScore,
    java.util.List<java.lang.String> holdingRegions)
  {
    this();
    this.regionServerIp = regionServerIp;
    this.port = port;
    setPortIsSet(true);
    this.loadScore = loadScore;
    setLoadScoreIsSet(true);
    this.holdingRegions = holdingRegions;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HeartbeatRequest(HeartbeatRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetRegionServerIp()) {
      this.regionServerIp = other.regionServerIp;
    }
    this.port = other.port;
    this.loadScore = other.loadScore;
    if (other.isSetHoldingRegions()) {
      java.util.List<java.lang.String> __this__holdingRegions = new java.util.ArrayList<java.lang.String>(other.holdingRegions);
      this.holdingRegions = __this__holdingRegions;
    }
  }

  @Override
  public HeartbeatRequest deepCopy() {
    return new HeartbeatRequest(this);
  }

  @Override
  public void clear() {
    this.regionServerIp = null;
    setPortIsSet(false);
    this.port = 0;
    setLoadScoreIsSet(false);
    this.loadScore = 0;
    this.holdingRegions = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getRegionServerIp() {
    return this.regionServerIp;
  }

  public HeartbeatRequest setRegionServerIp(@org.apache.thrift.annotation.Nullable java.lang.String regionServerIp) {
    this.regionServerIp = regionServerIp;
    return this;
  }

  public void unsetRegionServerIp() {
    this.regionServerIp = null;
  }

  /** Returns true if field regionServerIp is set (has been assigned a value) and false otherwise */
  public boolean isSetRegionServerIp() {
    return this.regionServerIp != null;
  }

  public void setRegionServerIpIsSet(boolean value) {
    if (!value) {
      this.regionServerIp = null;
    }
  }

  public int getPort() {
    return this.port;
  }

  public HeartbeatRequest setPort(int port) {
    this.port = port;
    setPortIsSet(true);
    return this;
  }

  public void unsetPort() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  /** Returns true if field port is set (has been assigned a value) and false otherwise */
  public boolean isSetPort() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  public void setPortIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PORT_ISSET_ID, value);
  }

  public int getLoadScore() {
    return this.loadScore;
  }

  public HeartbeatRequest setLoadScore(int loadScore) {
    this.loadScore = loadScore;
    setLoadScoreIsSet(true);
    return this;
  }

  public void unsetLoadScore() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LOADSCORE_ISSET_ID);
  }

  /** Returns true if field loadScore is set (has been assigned a value) and false otherwise */
  public boolean isSetLoadScore() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LOADSCORE_ISSET_ID);
  }

  public void setLoadScoreIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LOADSCORE_ISSET_ID, value);
  }

  public int getHoldingRegionsSize() {
    return (this.holdingRegions == null) ? 0 : this.holdingRegions.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getHoldingRegionsIterator() {
    return (this.holdingRegions == null) ? null : this.holdingRegions.iterator();
  }

  public void addToHoldingRegions(java.lang.String elem) {
    if (this.holdingRegions == null) {
      this.holdingRegions = new java.util.ArrayList<java.lang.String>();
    }
    this.holdingRegions.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getHoldingRegions() {
    return this.holdingRegions;
  }

  public HeartbeatRequest setHoldingRegions(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> holdingRegions) {
    this.holdingRegions = holdingRegions;
    return this;
  }

  public void unsetHoldingRegions() {
    this.holdingRegions = null;
  }

  /** Returns true if field holdingRegions is set (has been assigned a value) and false otherwise */
  public boolean isSetHoldingRegions() {
    return this.holdingRegions != null;
  }

  public void setHoldingRegionsIsSet(boolean value) {
    if (!value) {
      this.holdingRegions = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case REGION_SERVER_IP:
      if (value == null) {
        unsetRegionServerIp();
      } else {
        setRegionServerIp((java.lang.String)value);
      }
      break;

    case PORT:
      if (value == null) {
        unsetPort();
      } else {
        setPort((java.lang.Integer)value);
      }
      break;

    case LOAD_SCORE:
      if (value == null) {
        unsetLoadScore();
      } else {
        setLoadScore((java.lang.Integer)value);
      }
      break;

    case HOLDING_REGIONS:
      if (value == null) {
        unsetHoldingRegions();
      } else {
        setHoldingRegions((java.util.List<java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case REGION_SERVER_IP:
      return getRegionServerIp();

    case PORT:
      return getPort();

    case LOAD_SCORE:
      return getLoadScore();

    case HOLDING_REGIONS:
      return getHoldingRegions();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case REGION_SERVER_IP:
      return isSetRegionServerIp();
    case PORT:
      return isSetPort();
    case LOAD_SCORE:
      return isSetLoadScore();
    case HOLDING_REGIONS:
      return isSetHoldingRegions();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof HeartbeatRequest)
      return this.equals((HeartbeatRequest)that);
    return false;
  }

  public boolean equals(HeartbeatRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_regionServerIp = true && this.isSetRegionServerIp();
    boolean that_present_regionServerIp = true && that.isSetRegionServerIp();
    if (this_present_regionServerIp || that_present_regionServerIp) {
      if (!(this_present_regionServerIp && that_present_regionServerIp))
        return false;
      if (!this.regionServerIp.equals(that.regionServerIp))
        return false;
    }

    boolean this_present_port = true;
    boolean that_present_port = true;
    if (this_present_port || that_present_port) {
      if (!(this_present_port && that_present_port))
        return false;
      if (this.port != that.port)
        return false;
    }

    boolean this_present_loadScore = true;
    boolean that_present_loadScore = true;
    if (this_present_loadScore || that_present_loadScore) {
      if (!(this_present_loadScore && that_present_loadScore))
        return false;
      if (this.loadScore != that.loadScore)
        return false;
    }

    boolean this_present_holdingRegions = true && this.isSetHoldingRegions();
    boolean that_present_holdingRegions = true && that.isSetHoldingRegions();
    if (this_present_holdingRegions || that_present_holdingRegions) {
      if (!(this_present_holdingRegions && that_present_holdingRegions))
        return false;
      if (!this.holdingRegions.equals(that.holdingRegions))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetRegionServerIp()) ? 131071 : 524287);
    if (isSetRegionServerIp())
      hashCode = hashCode * 8191 + regionServerIp.hashCode();

    hashCode = hashCode * 8191 + port;

    hashCode = hashCode * 8191 + loadScore;

    hashCode = hashCode * 8191 + ((isSetHoldingRegions()) ? 131071 : 524287);
    if (isSetHoldingRegions())
      hashCode = hashCode * 8191 + holdingRegions.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(HeartbeatRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetRegionServerIp(), other.isSetRegionServerIp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRegionServerIp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.regionServerIp, other.regionServerIp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPort(), other.isSetPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.port, other.port);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLoadScore(), other.isSetLoadScore());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLoadScore()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.loadScore, other.loadScore);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetHoldingRegions(), other.isSetHoldingRegions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHoldingRegions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.holdingRegions, other.holdingRegions);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("HeartbeatRequest(");
    boolean first = true;

    sb.append("regionServerIp:");
    if (this.regionServerIp == null) {
      sb.append("null");
    } else {
      sb.append(this.regionServerIp);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("port:");
    sb.append(this.port);
    first = false;
    if (!first) sb.append(", ");
    sb.append("loadScore:");
    sb.append(this.loadScore);
    first = false;
    if (!first) sb.append(", ");
    sb.append("holdingRegions:");
    if (this.holdingRegions == null) {
      sb.append("null");
    } else {
      sb.append(this.holdingRegions);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HeartbeatRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public HeartbeatRequestStandardScheme getScheme() {
      return new HeartbeatRequestStandardScheme();
    }
  }

  private static class HeartbeatRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<HeartbeatRequest> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, HeartbeatRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REGION_SERVER_IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.regionServerIp = iprot.readString();
              struct.setRegionServerIpIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.port = iprot.readI32();
              struct.setPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LOAD_SCORE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.loadScore = iprot.readI32();
              struct.setLoadScoreIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // HOLDING_REGIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.holdingRegions = new java.util.ArrayList<java.lang.String>(_list0.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readString();
                  struct.holdingRegions.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setHoldingRegionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, HeartbeatRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.regionServerIp != null) {
        oprot.writeFieldBegin(REGION_SERVER_IP_FIELD_DESC);
        oprot.writeString(struct.regionServerIp);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PORT_FIELD_DESC);
      oprot.writeI32(struct.port);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LOAD_SCORE_FIELD_DESC);
      oprot.writeI32(struct.loadScore);
      oprot.writeFieldEnd();
      if (struct.holdingRegions != null) {
        oprot.writeFieldBegin(HOLDING_REGIONS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.holdingRegions.size()));
          for (java.lang.String _iter3 : struct.holdingRegions)
          {
            oprot.writeString(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HeartbeatRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public HeartbeatRequestTupleScheme getScheme() {
      return new HeartbeatRequestTupleScheme();
    }
  }

  private static class HeartbeatRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<HeartbeatRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HeartbeatRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetRegionServerIp()) {
        optionals.set(0);
      }
      if (struct.isSetPort()) {
        optionals.set(1);
      }
      if (struct.isSetLoadScore()) {
        optionals.set(2);
      }
      if (struct.isSetHoldingRegions()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetRegionServerIp()) {
        oprot.writeString(struct.regionServerIp);
      }
      if (struct.isSetPort()) {
        oprot.writeI32(struct.port);
      }
      if (struct.isSetLoadScore()) {
        oprot.writeI32(struct.loadScore);
      }
      if (struct.isSetHoldingRegions()) {
        {
          oprot.writeI32(struct.holdingRegions.size());
          for (java.lang.String _iter4 : struct.holdingRegions)
          {
            oprot.writeString(_iter4);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HeartbeatRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.regionServerIp = iprot.readString();
        struct.setRegionServerIpIsSet(true);
      }
      if (incoming.get(1)) {
        struct.port = iprot.readI32();
        struct.setPortIsSet(true);
      }
      if (incoming.get(2)) {
        struct.loadScore = iprot.readI32();
        struct.setLoadScoreIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.holdingRegions = new java.util.ArrayList<java.lang.String>(_list5.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = iprot.readString();
            struct.holdingRegions.add(_elem6);
          }
        }
        struct.setHoldingRegionsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

